[program]
entry_point = "./src/main.cpp"
files = "./src/*.cpp"
output = "./bin/program"
arguments = "-ggdb -std=c++20 -Wall -Wextra -Wfloat-equal -Wshadow -Wconversion -Wpedantic -fsanitize=undefined,address"

[release]
entry_point = "./src/main.cpp"
files = "./src/*.cpp"
output = "./bin/release"
arguments = "-O2 -DNDEBUG -std=c++20 -Wall -Wextra -Wfloat-equal -Wshadow -Wconversion -Wpedantic -fsanitize=undefined,address"

[SOLUTION]
executable = "./bin/program"
